export const APP_MODES = Object.freeze({
  OFFICIAL: 'official',
  SCRAPER: 'scraper',
  HYBRID: 'hybrid'
});

export const REQUEST_SOURCES = Object.freeze({
  AUTO: 'auto',
  OFFICIAL: 'official',
  SCRAPER: 'scraper'
});

export const ERROR_CODES = Object.freeze({
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  USERNAME_INVALID: 'USERNAME_INVALID',
  MODE_INVALID: 'MODE_INVALID',
  OFFICIAL_DISABLED: 'OFFICIAL_DISABLED',
  SCRAPER_DISABLED: 'SCRAPER_DISABLED',
  META_CONFIG_MISSING: 'META_CONFIG_MISSING',
  META_USERNAME_MISMATCH: 'META_USERNAME_MISMATCH',
  META_API_ERROR: 'META_API_ERROR',
  PUPPETEER_NOT_INSTALLED: 'PUPPETEER_NOT_INSTALLED',
  SCRAPER_ERROR: 'SCRAPER_ERROR',
  TIMEOUT: 'TIMEOUT',
  OPERATION_DRY_RUN: 'OPERATION_DRY_RUN',
  RESOURCE_UNAVAILABLE: 'RESOURCE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
});

export const INSTAGRAM_USERNAME_REGEX = /^[A-Za-z0-9._]{1,30}$/;
export const API_VERSION = 'v1';
